const data = [
  {
    suitName: "曹操套",
    suitBuffName: "超世之杰",
    type: "重甲",
    against: "火",
    eName: [
      { eName: "倚天剑" },
      { eName: "奸雄小冠" },
      { eName: "奸雄战凯" },
      { eName: "奸雄臂甲" },
      { eName: "奸雄胫甲" },
      { eName: "孙子略解" },
    ],
    buff: [
      { buffName: "打倒敌人获得的士气点数", number: 4.0 },
      { buffName: "察觉旌旗" },
      { buffName: "绝技命中时使敌人移动减速" },
      { buffName: "剑气势伤害", number: 9.8 },
      { buffName: "绝技命中时使敌人气势衰微" },
    ],
  },
  {
    suitName: "程普套",
    suitBuffName: "孙氏老臣",
    type: "中甲",
    against: "金",
    eName: [
      { eName: "铁脊蛇矛" },
      { eName: "首席虎臣帻冠" },
      { eName: "首席虎臣中铠" },
      { eName: "首席虎臣臂甲" },
      { eName: "首席虎臣胫甲" },
    ],
    buff: [
      { buffName: "气势维持", number: 12 },
      { buffName: "绝脉成功时解除不利效果" },
      { buffName: "绝技的消耗气势", number: -3.0 },
      { buffName: "绝技的气势伤害", number: 9.0 },
    ],
  },
  {
    suitName: "董卓套",
    suitBuffName: "逆天灭道",
    type: "轻甲",
    against: "水金",
    eName: [
      { eName: "神胜万里伏" },
      { eName: "暴虐霸者头环" },
      { eName: "暴虐霸者战袍" },
      { eName: "暴虐霸者臂甲" },
      { eName: "暴虐霸者胫甲" },
    ],
    buff: [
      { buffName: "体力", number: 12 },
      { buffName: "绝脉成功时，为敌人附加威力低落" },
      { buffName: "吸取体力(近战)", number: "E" },
      { buffName: "对身负不利效果之敌人气势伤害", number: 9.8 },
    ],
  },
  {
    suitName: "关羽套",
    suitBuffName: "义薄云天",
    type: "重甲",
    against: "木",
    eName: [
      { eName: "青龙偃月刀" },
      { eName: "美髯公帻冠" },
      { eName: "美髯公战凯" },
      { eName: "美髯公臂甲" },
      { eName: "美髯公胫甲" },
    ],
    buff: [
      { buffName: "化解时获得的气势", number: 2.8 },
      { buffName: "绝技的消耗气势", number: -2.2 },
      { buffName: "化解杀招成功时减轻负伤" },
      { buffName: "大刀伤害", number: 8.3 },
    ],
  },
  {
    suitName: "郭嘉套",
    suitBuffName: "世之奇士",
    type: "轻甲",
    against: "土木",
    eName: [
      { eName: "鸱鸮杖" },
      { eName: "郭祭酒小冠" },
      { eName: "郭祭酒氅衣" },
      { eName: "郭祭酒手衣" },
      { eName: "郭祭酒足履" },
      { eName: "错银博琼" },
    ],
    buff: [
      { buffName: "敌人异常状态累积量", number: 4.8 },
      { buffName: "绝脉成功时，为敌人附加威力低落" },
      { buffName: "延长敌人不利效果", number: 4.2 },
      { buffName: "绝脉成功时，为敌人附加负伤加重" },
      { buffName: "对身负不利效果之敌人伤害", number: 13.2 },
    ],
  },
  {
    suitName: "韩当套",
    suitBuffName: "先登敢死",
    type: "重甲",
    against: "水",
    eName: [
      { eName: "卷首大刀" },
      { eName: "敢死虎臣兜鍪" },
      { eName: "敢死虎臣战铠" },
      { eName: "敢死虎臣臂甲" },
      { eName: "敢死虎臣胫甲" },
    ],
    buff: [
      { buffName: "因攻击而承受的伤害", number: -1.6 },
      { buffName: "格挡时失去的气势", number: -2.8 },
      { buffName: "绝技命中时威力上升" },
      { buffName: "无伤时气势伤害", number: 12.8 },
    ],
  },
  {
    suitName: "红晶套",
    suitBuffName: "天柱道法",
    type: "轻甲",
    against: "木金",
    eName: [
      { eName: "翡翠枝" },
      { eName: "天柱派竹笠" },
      { eName: "天柱派羽衣" },
      { eName: "天柱派护腕" },
      { eName: "天柱派足履" },
    ],
    buff: [
      { buffName: "体力", number: 12 },
      { buffName: "奇术的消耗气势", number: -2.2 },
      { buffName: "奇术命中时威力上升" },
      { buffName: "棍杖气势伤害", number: 9.8 },
    ],
  },
  {
    suitName: "华雄套",
    suitBuffName: "熊罴猛将",
    type: "重甲",
    against: "金",
    eName: [
      { eName: "飞熊刚殳" },
      { eName: "跋扈兜鍪" },
      { eName: "跋扈战铠" },
      { eName: "跋扈臂甲" },
      { eName: "跋扈胫甲" },
    ],
    buff: [
      { buffName: "化解时获得的气势", number: 2.8 },
      { buffName: "承受的气势伤害", number: -2.4 },
      { buffName: "化解成功时减轻负伤" },
      { buffName: "绝技伤害", number: 7.5 },
    ],
  },
  {
    suitName: "黄盖套",
    suitBuffName: "智勇双全",
    type: "轻甲",
    against: "火土",
    eName: [
      { eName: "阖闾金钩" },
      { eName: "持重虎臣帻冠" },
      { eName: "持重虎臣轻甲" },
      { eName: "持重虎臣臂甲" },
      { eName: "持重虎臣足履" },
    ],
    buff: [
      { buffName: "隐蔽性", number: 24 },
      { buffName: "绝脉伤害", number: 3.5 },
      { buffName: "绝脉成功时气势旺盛" },
      { buffName: "双刀气势伤害", number: 9.8 },
    ],
  },
  {
    suitName: "刘备套",
    suitBuffName: "兴汉之志",
    type: "中甲",
    against: "木",
    eName: [
      { eName: "双股剑" },
      { eName: "仁者小冠" },
      { eName: "仁者中甲" },
      { eName: "仁者臂甲" },
      { eName: "仁者足履" },
      { eName: "织草长结" },
    ],
    buff: [
      { buffName: "体力", number: 12 },
      { buffName: "化解成功时恢复体力", number: 6 },
      { buffName: "无伤时承受气势伤害", number: -5.4 },
      { buffName: "恢复体力时气势旺盛" },
      { buffName: "无伤时伤害", number: 17.2 },
    ],
  },
  {
    suitName: "吕布套",
    suitBuffName: "人中吕布",
    type: "中甲",
    against: "土",
    eName: [
      { eName: "方天画戟" },
      { eName: "飞将之弓" },
      { eName: "飞将面罩" },
      { eName: "飞将战铠" },
      { eName: "飞将臂甲" },
      { eName: "飞将胫甲" },
    ],
    buff: [
      { buffName: "体力", number: 12 },
      { buffName: "察觉敌人" },
      { buffName: "绝技的消耗气势", number: -3.0 },
      { buffName: "戟气势伤害", number: 9.8 },
      { buffName: "绝技伤害", number: 12.0 },
    ],
  },
  {
    suitName: "孙策套",
    suitBuffName: "𤟰儿骁勇",
    type: "轻甲",
    against: "木火金",
    eName: [
      { eName: "虎牙双戟" },
      { eName: "小霸王头带" },
      { eName: "小霸王战衣" },
      { eName: "小霸王臂甲" },
      { eName: "小霸王胫甲" },
    ],
    buff: [
      { buffName: "基本攻击时的气势获取量", number: 2.4 },
      { buffName: "攻击动作中承受的伤害", number: -2.4 },
      { buffName: "化解杀招成功时使敌人负伤加重" },
      { buffName: "双戟伤害", number: 8.3 },
    ],
  },
  {
    suitName: "孙坚套",
    suitBuffName: "江东之虎",
    type: "重甲",
    against: "金",
    eName: [
      { eName: "古锭刀" },
      { eName: "猛虎铁胄" },
      { eName: "猛虎战铠" },
      { eName: "猛虎臂甲" },
      { eName: "猛虎胫甲" },
    ],
    buff: [
      { buffName: "气势维持", number: 12 },
      { buffName: "化解时获得的气势", number: 3.4 },
      { buffName: "绝脉成功时气势旺盛" },
      { buffName: "气势攻击伤害", number: 7.5 },
    ],
  },
  {
    suitName: "孙权套",
    suitBuffName: "猛虎之后",
    type: "中甲",
    against: "火",
    eName: [
      { eName: "白虹" },
      { eName: "射虎弓" },
      { eName: "碧眼儿兜鍪" },
      { eName: "碧眼儿中甲" },
      { eName: "碧眼儿臂甲" },
      { eName: "碧眼儿胫甲" },
    ],
    buff: [
      { buffName: "弓箭弹药持有上限", number: 2 },
      { buffName: "远程攻击命中时回收箭矢", number: 6.0 },
      { buffName: "绝技的消耗气势", number: -3.0 },
      { buffName: "近战伤害", number: 6.5 },
      { buffName: "远程攻击命中时，对敌人附加负伤加重" },
    ],
  },
  {
    suitName: "文丑套",
    suitBuffName: "勇冠三军之誉",
    type: "重甲",
    against: "土",
    eName: [
      { eName: "鵹鹕嘴槌" },
      { eName: "河间煞星兜鍪" },
      { eName: "河间煞星战铠" },
      { eName: "河间煞星臂甲" },
      { eName: "河间煞星胫甲" },
    ],
    buff: [
      { buffName: "因攻击而承受的伤害", number: -1.6 },
      { buffName: "格挡时失去的气势", number: -2.8 },
      { buffName: "攻击动作重承受的气势伤害", number: -4.2 },
      { buffName: "大槌气势伤害", number: 9.8 },
    ],
  },
  {
    suitName: "夏侯惇套",
    suitBuffName: "奸雄股肱",
    type: "中甲",
    against: "火",
    eName: [
      { eName: "朱雀天钺" },
      { eName: "刚烈兜鍪" },
      { eName: "刚烈中铠" },
      { eName: "刚烈手衣" },
      { eName: "刚烈胫甲" },
    ],
    buff: [
      { buffName: "异常状态抗性", number: 4.8 },
      { buffName: "攻击动作中承受的气势伤害", number: -3.0 },
      { buffName: "消耗气势", number: -2.6 },
      { buffName: "斧钺伤害", number: 8.3 },
    ],
  },
  {
    suitName: "夏侯渊套",
    suitBuffName: "赴急疾",
    type: "中甲",
    against: "金",
    eName: [
      { eName: "天狼" },
      { eName: "羽林骑弓" },
      { eName: "急袭兜鍪" },
      { eName: "急袭中铠" },
      { eName: "急袭臂甲" },
      { eName: "急袭胫甲" },
    ],
    buff: [
      { buffName: "弓箭弹药持有上限", number: 2 },
      { buffName: "绝脉成功时补充箭矢", number: 2 },
      { buffName: "远程攻击命中时回收箭矢", number: 8.4 },
      { buffName: "远程攻击命中时，对敌人附加移动减缓" },
      { buffName: "射击武器伤害", number: 16.8 },
    ],
  },
  {
    suitName: "荀彧套",
    suitBuffName: "王佐之才",
    type: "轻甲",
    against: "木火土",
    eName: [
      { eName: "圣心" },
      { eName: "荀令君白帢" },
      { eName: "荀令君帛衣" },
      { eName: "荀令君手衣" },
      { eName: "荀令君足履" },
      { eName: "象牙熏笼" },
    ],
    buff: [
      { buffName: "真气获得量", number: 6.4 },
      { buffName: "体力恢复量", number: 2.0 },
      { buffName: "有利效果持续", number: 4.2 },
      { buffName: "绝脉成功时再生" },
      { buffName: "附上属性的武器造成的伤害", number: 14.0 },
    ],
  },
  {
    suitName: "颜良套",
    suitBuffName: "袁氏首席上将",
    type: "中甲",
    against: "土",
    eName: [
      { eName: "魃骨刀" },
      { eName: "河间凶星头带" },
      { eName: "河间凶星中凯" },
      { eName: "河间凶星臂甲" },
      { eName: "河间凶星胫甲" },
    ],
    buff: [
      { buffName: "基本攻击时的气势获得量", number: 2.4 },
      { buffName: "化解的消耗气势", number: -2.2 },
      { buffName: "化解成功时气势旺盛" },
      { buffName: "曲刀伤害", number: 8.3 },
    ],
  },
  {
    suitName: "于吉套",
    suitBuffName: "妖言惑众",
    type: "轻甲",
    against: "木火金",
    eName: [
      { eName: "禹王剑" },
      { eName: "邪法道士头饰" },
      { eName: "邪法道士法袍" },
      { eName: "邪法道士腕饰" },
      { eName: "邪法道士足饰" },
    ],
    buff: [
      { buffName: "化解时获得的气势", number: 2.8 },
      { buffName: "属性伤害", number: 3.0 },
      { buffName: "奇术命中时使敌人负伤加重" },
      { buffName: "奇术伤害", number: 8.3 },
    ],
  },
  {
    suitName: "张飞套",
    suitBuffName: "万人敌",
    type: "轻甲",
    against: "木火水",
    eName: [
      { eName: "丈八蛇矛" },
      { eName: "猛张飞头带" },
      { eName: "猛张飞轻甲" },
      { eName: "猛张飞臂甲" },
      { eName: "猛张飞足履" },
    ],
    buff: [
      { buffName: "绝技的消耗气势", number: -1.8 },
      { buffName: "获得气势", number: 2.4 },
      { buffName: "攻击动作中承受的伤害", number: -3.4 },
      { buffName: "绝技伤害", number: 7.5 },
    ],
  },
  {
    suitName: "张梁套",
    suitBuffName: "黄天当立",
    type: "轻甲",
    against: "木火土",
    eName: [
      { eName: "太一杵棒" },
      { eName: "人公将军头巾" },
      { eName: "人公将军轻甲" },
      { eName: "人公将军臂甲" },
      { eName: "人公将军胫甲" },
    ],
    buff: [
      { buffName: "基本攻击时的气势获得量", number: 2.4 },
      { buffName: "攻击动作中承受的气势伤害", number: -3.0 },
      { buffName: "化解成功时强伤" },
      { buffName: "近战气势伤害", number: 8.0 },
    ],
  },
  {
    suitName: "张辽套",
    suitBuffName: "古之召虎",
    type: "中甲",
    against: "木",
    eName: [
      { eName: "雕虎" },
      { eName: "锋锐兜鍪" },
      { eName: "锋锐中铠" },
      { eName: "锋锐臂甲" },
      { eName: "锋锐胫甲" },
    ],
    buff: [
      { buffName: "绝技的消耗气势", number: -1.8 },
      { buffName: "绝技命中时移动加速" },
      { buffName: "绝脉成功时威力上升" },
      { buffName: "直刀伤害", number: 8.3 },
    ],
  },
  {
    suitName: "赵云套",
    suitBuffName: "一身是胆",
    type: "中甲",
    against: "水",
    eName: [
      { eName: "涯角枪" },
      { eName: "豪胆兜鍪" },
      { eName: "豪胆中铠" },
      { eName: "豪胆臂甲" },
      { eName: "豪胆胫甲" },
    ],
    buff: [
      { buffName: "化解的消耗气势", number: -1.8 },
      { buffName: "打倒敌人获得的士气点数", number: 5.0 },
      { buffName: "化解成功时威力上升" },
      { buffName: "枪伤害", number: 8.3 },
    ],
  },
];
export default data;
